### ISSUE TITLE
Overrides container coloring

### ISSUE THREAD

**Issue by Titaniumtown** [HliasOuzounis/zen-browser-better-active-tab-indicator#1]
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/b6b1ae17-9e93-42ce-b7c3-712065b1ee49) | ![image](https://github.com/user-attachments/assets/f5a6699c-2ca9-48cd-b4b8-309315e5dbbd) |

The container tab should still be colored!

**Comment by HliasOuzounis** [comment]
You're right, and I'm sorry that I didn't test this.

Unfortunately since both the container indicator and this active tab indicator use the same element (.tabbrowser-tab::after) it's impossible to configure them both without inserting a new element which user created themes can't afiak.

I'll update the readme.

**Comment by HliasOuzounis** [comment]
![image](https://github.com/user-attachments/assets/39e3bbb0-d5f3-41a4-9a4b-fc56ec7f6fd2)

With the new update it seems to work now. If your active tab also is in a container, the active tab indicator gets priority but otherwise container coloring is visible.

The theme isn't updated on the theme store yet, waiting for the merge.

**Comment by jasiralavibiztripz** [comment]
Can we have an option to move the indicator the the right side? 
Just as an option.
That way it highlights the active tab better and we can know the container as well.
